# IMPLEMENTS REQUIREMENTS:
#   REQ-o00056: Container infrastructure for Cloud Run
#   REQ-d00028: Portal Frontend Framework
#
# Cloud Build configuration for Sponsor Portal container
# Builds Flutter web UI + Dart server, pushes to Artifact Registry in Europe (GDPR compliance)
#
# Versions come from .github/versions.env (single source of truth)

substitutions:
  _REGION: 'europe-west1'
  _REPOSITORY: 'hht-diary'

steps:
  # Step 1: Load versions from versions.env
  - name: 'bash'
    id: 'load-versions'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source .github/versions.env
        echo "DART_VERSION=$${DART_VERSION}" > /workspace/versions.txt
        echo "FLUTTER_VERSION=$${FLUTTER_VERSION}" >> /workspace/versions.txt
        echo "Building sponsor-portal with Dart $${DART_VERSION}, Flutter $${FLUTTER_VERSION}"

  # Step 2: Build the sponsor portal image (Flutter web + Dart server)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/versions.txt
        docker build \
          --build-arg=DART_VERSION=$${DART_VERSION} \
          --build-arg=FLUTTER_VERSION=$${FLUTTER_VERSION} \
          --build-arg=GCP_PROJECT_ID=${PROJECT_ID} \
          -f apps/sponsor-portal/portal-container/Dockerfile \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/sponsor-portal:$${DART_VERSION}-${SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/sponsor-portal:latest \
          .

  # Step 3: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/versions.txt
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/sponsor-portal:$${DART_VERSION}-${SHORT_SHA}
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/sponsor-portal:latest

options:
  logging: CLOUD_LOGGING_ONLY
  # Larger machine for Flutter build
  machineType: 'E2_HIGHCPU_8'
