name: portal-cloud
description: Clinical Trial Portal Infrastructure (Multi-Environment, Multi-Sponsor)
runtime: nodejs

# IMPLEMENTS REQUIREMENTS:
#   REQ-o00056: Pulumi IaC for portal deployment
#   REQ-p00042: Infrastructure audit trail

config:
  gcp:project:
    description: GCP Project ID for this sponsor environment
    type: string
  gcp:region:
    description: GCP region for resource deployment
    type: string
    default: us-central1
  sponsor:
    description: Sponsor name (e.g., orion, callisto)
    type: string
  environment:
    description: Environment type (dev, qa, uat, prod)
    type: string
  domainName:
    description: Custom domain for portal (e.g., portal-orion.cure-hht.org)
    type: string
  dbPassword:
    description: Cloud SQL PostgreSQL password
    type: string
    secret: true
  sponsorRepoPath:
    description: Path to sponsor-specific repository
    type: string
    default: ../clinical-diary-sponsor
  minInstances:
    description: Minimum Cloud Run instances (0 for dev, 1+ for prod)
    type: number
    default: 1
  maxInstances:
    description: Maximum Cloud Run instances
    type: number
    default: 10
  containerMemory:
    description: Cloud Run container memory (e.g., 512Mi, 1Gi)
    type: string
    default: 512Mi
  containerCpu:
    description: Cloud Run container CPU count
    type: number
    default: 1

backend:
  url: gs://pulumi-state-cure-hht
