// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2dMGCSQ_At7jb-v0v7jdCwHLqZexvOU',
    appId: '1:681337116402:web:4623da2691399d14f5626b',
    messagingSenderId: '681337116402',
    projectId: 'hht-diary-mvp',
    authDomain: 'hht-diary-mvp.firebaseapp.com',
    storageBucket: 'hht-diary-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3HU6MSI_iC6PMG-LzmddmchdjvwgeieA',
    appId: '1:681337116402:android:bf70f4aaf5ebdddbf5626b',
    messagingSenderId: '681337116402',
    projectId: 'hht-diary-mvp',
    storageBucket: 'hht-diary-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbQRWQSsTqKwQM3X8daoqFQIUdHYS46Ns',
    appId: '1:681337116402:ios:d5d97d26841d2b4ef5626b',
    messagingSenderId: '681337116402',
    projectId: 'hht-diary-mvp',
    storageBucket: 'hht-diary-mvp.firebasestorage.app',
    iosBundleId: 'org.curehht.clinicalDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbQRWQSsTqKwQM3X8daoqFQIUdHYS46Ns',
    appId: '1:681337116402:ios:d5d97d26841d2b4ef5626b',
    messagingSenderId: '681337116402',
    projectId: 'hht-diary-mvp',
    storageBucket: 'hht-diary-mvp.firebasestorage.app',
    iosBundleId: 'org.curehht.clinicalDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2dMGCSQ_At7jb-v0v7jdCwHLqZexvOU',
    appId: '1:681337116402:web:bb34262b09289600f5626b',
    messagingSenderId: '681337116402',
    projectId: 'hht-diary-mvp',
    authDomain: 'hht-diary-mvp.firebaseapp.com',
    storageBucket: 'hht-diary-mvp.firebasestorage.app',
  );
}