// IMPLEMENTS REQUIREMENTS:
//   REQ-d00005: Sponsor Configuration Detection Implementation

/// Flavor configuration for the Clinical Diary app.
///
/// This file defines the flavor-specific settings. All configuration
/// (API endpoints, feature flags) is derived from the flavor name.
///
/// Usage:
///   # For web builds (--flavor doesn't work on web):
///   flutter run -d chrome --dart-define=APP_FLAVOR=dev
///
///   # For mobile builds (both work, --flavor sets FLUTTER_APP_FLAVOR):
///   flutter run --flavor dev --dart-define=APP_FLAVOR=dev
///
/// The app reads APP_FLAVOR (or FLUTTER_APP_FLAVOR on mobile) in main.dart
/// and uses FlavorConfig to derive all other settings (apiBase, etc.).
///
/// See also:
/// - lib/main.dart - Flavor initialization
/// - lib/config/app_config.dart - App configuration (uses FlavorConfig)
/// - .idea/runConfigurations/ - IntelliJ IDEA configurations
/// - .vscode/launch.json - VSCode configurations
library;

/// Available app flavors/environments.
enum Flavor { dev, qa, uat, prod }

/// Flavor accessor class generated by flutter_flavorizr.
class F {
  F._();

  static Flavor? _appFlavor;

  static Flavor get appFlavor {
    if (_appFlavor == null) {
      throw StateError(
        'Flavor not set. Ensure F.appFlavor is set in main() before accessing.',
      );
    }
    return _appFlavor!;
  }

  static set appFlavor(Flavor value) => _appFlavor = value;

  static String get name => appFlavor.name;

  static String get title {
    switch (appFlavor) {
      case Flavor.dev:
        return 'Diary DEV';
      case Flavor.qa:
        return 'Diary QA';
      case Flavor.uat:
        return 'Clinical Diary';
      case Flavor.prod:
        return 'Clinical Diary';
    }
  }

  /// Whether dev tools (Reset Data, Add Example Data) should be shown.
  static bool get showDevTools {
    switch (appFlavor) {
      case Flavor.dev:
      case Flavor.qa:
        return true;
      case Flavor.uat:
      case Flavor.prod:
        return false;
    }
  }

  /// Whether the environment banner should be shown.
  static bool get showBanner {
    switch (appFlavor) {
      case Flavor.dev:
      case Flavor.qa:
        return true;
      case Flavor.uat:
      case Flavor.prod:
        return false;
    }
  }
}

/// Flavor definitions with their dart-define values.
///
/// These are used by build scripts and CI/CD to ensure correct configuration.
class FlavorConfig {
  FlavorConfig._();

  /// Development flavor configuration
  static const dev = FlavorValues(
    name: 'dev',
    apiBase: 'https://hht-diary-mvp.web.app/api',
    environment: 'dev',
    showDevTools: true,
    showBanner: true,
  );

  /// QA flavor configuration
  static const qa = FlavorValues(
    name: 'qa',
    apiBase: 'https://hht-diary-qa.web.app/api',
    environment: 'qa',
    showDevTools: true,
    showBanner: true,
  );

  /// UAT flavor configuration
  /// NOTE: Temporarily pointing to MVP backend for pre-UAT release
  static const uat = FlavorValues(
    name: 'uat',
    apiBase: 'https://hht-diary-mvp.web.app/api',
    environment: 'uat',
    showDevTools: false,
    showBanner: false,
  );

  /// Production flavor configuration
  static const prod = FlavorValues(
    name: 'prod',
    apiBase: 'https://hht-diary.web.app/api',
    environment: 'prod',
    showDevTools: false,
    showBanner: false,
  );

  /// Get flavor by name
  static FlavorValues byName(String name) {
    return switch (name.toLowerCase()) {
      'dev' => dev,
      'qa' => qa,
      'uat' => uat,
      'prod' => prod,
      _ => dev, // Default to dev
    };
  }

  /// All available flavors
  static const all = [dev, qa, uat, prod];
}

/// Immutable flavor configuration values
class FlavorValues {
  const FlavorValues({
    required this.name,
    required this.apiBase,
    required this.environment,
    required this.showDevTools,
    required this.showBanner,
  });

  final String name;
  final String apiBase;
  final String environment;
  final bool showDevTools;
  final bool showBanner;

  /// Generate dart-define argument for this flavor.
  /// Only APP_FLAVOR is needed - all other config is derived from FlavorConfig.
  String get dartDefine => '--dart-define=APP_FLAVOR=$name';
}
